### ISSUE TITLE
Seminário I - TCC II

### ISSUE THREAD

**Issue by edeciofernando** [gabrielgcaetano/comidabarata#8]
- Sugestões
* [x]  Ofertas de sustentabilidade (indicar o que é)
* [x]  Estrelas no produto (produto ou empresa)?

**Comment by gabrielgcaetano** [comment]
Foi colocado uma descrição ao lado do titulo informando que o produto está próximo a validade.

**Comment by gabrielgcaetano** [comment]
Vai ser implementada uma pontuação á empresa, quando essa funcionalidade estiver implementada.
